/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg:      '#07090d',
        s1:      '#0c1017',
        s2:      '#111820',
        s3:      '#182030',
        border1: '#1e2d3d',
        border2: '#2a3f55',
        text:    '#c8d8e8',
        muted:   '#4a6272',
        dim:     '#2a3a4a',
        green:   '#00e676',
        yellow:  '#ffd740',
        red:     '#ff3d3d',
        cyan:    '#00b8d9',
        orange:  '#ff6d00',
      },
      fontFamily: {
        heading: ['Syne', 'sans-serif'],
        mono:    ['DM Mono', 'monospace'],
        body:    ['DM Sans', 'sans-serif'],
      },
      keyframes: {
        fadeUp:    { from: { opacity: '0', transform: 'translateY(12px)' } },
        pulse:     { '0%,100%': { boxShadow: '0 0 0 0 rgba(0,230,118,0.4)' }, '50%': { boxShadow: '0 0 0 4px rgba(0,230,118,0)' } },
        blink:     { '50%': { opacity: '0' } },
        pinPulse:  { '0%': { opacity: '0.8', transform: 'scale(1)' }, '100%': { opacity: '0', transform: 'scale(2)' } },
        slideIn:   { from: { opacity: '0', transform: 'translateX(-8px)' } },
        toastIn:   { from: { opacity: '0', transform: 'translateX(20px)' } },
        toastOut:  { to:   { opacity: '0', transform: 'translateX(20px)' } },
        modalIn:   { from: { opacity: '0', transform: 'scale(0.96)' } },
      },
      animation: {
        fadeUp:   'fadeUp 0.5s ease-out both',
        pulse:    'pulse 2s infinite',
        blink:    'blink 1s step-end infinite',
        pinPulse: 'pinPulse 2s ease-out infinite',
        slideIn:  'slideIn 0.3s ease-out',
        toastIn:  'toastIn 0.3s ease-out',
        toastOut: 'toastOut 0.3s ease-in forwards',
        modalIn:  'modalIn 0.2s ease-out',
      },
    },
  },
  plugins: [],
}
